name: Test & Build
on:
  workflow_dispatch:

jobs:         
  build-production:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v3.5.3
          with:
            fetch-depth: 0
        - name: Get tags
          run: git fetch --tags origin
        - name: Setup Node
          uses: actions/setup-node@v3
          with:
              node-version: "20"
        - name: Install Deps
          env:
            NODE_ENV: test
          run: yarn install --ignore-scripts
        - name: Build
          env:
            NODE_ENV: production
          run: |
              yarn build
              yarn manage:translations en
        - name: Upload a Build Artifact
          uses: actions/upload-artifact@v3.1.2
          with:
            # Artifact name
            name: soapbox-fe
            # A file, directory or wildcard pattern that describes what to upload
            path: static
            retention-days: 5
          
